"""add aaa, job, log_template

Revision ID: a7c8a4717908
Revises: 
Create Date: 2025-09-01 13:41:51.536862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c8a4717908'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aaa_permissions',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aaa_permissions_name'), 'aaa_permissions', ['name'], unique=True)
    op.create_table('aaa_roles',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aaa_roles_name'), 'aaa_roles', ['name'], unique=True)
    op.create_table('log_templates',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique, human-readable name for the template'),
    sa.Column('device_type', sa.String(length=100), nullable=False, comment="Device type for categorizing the template (e.g., 'FortiGate')"),
    sa.Column('content_format', sa.Text(), nullable=False, comment='The log format string for this template'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description providing more context for the template'),
    sa.Column('is_predefined', sa.Boolean(), nullable=False, comment='Flag to distinguish between system-provided and user-custom templates'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_templates_device_type'), 'log_templates', ['device_type'], unique=False)
    op.create_index(op.f('ix_log_templates_name'), 'log_templates', ['name'], unique=True)
    op.create_table('aaa_accounts',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('password_hashed', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['aaa_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_index(op.f('ix_aaa_accounts_email'), 'aaa_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_aaa_accounts_username'), 'aaa_accounts', ['username'], unique=True)
    op.create_table('aaa_role_permission',
    sa.Column('role_id', sa.String(length=64), nullable=True),
    sa.Column('permission_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['aaa_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['aaa_roles.id'], )
    )
    op.create_table('jobs',
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.Enum('TCP', 'UDP', name='protocolenum'), nullable=False, comment='Network protocol (TCP or UDP)'),
    sa.Column('destination_host', sa.String(length=255), nullable=False, comment='Target host IP address or hostname'),
    sa.Column('destination_port', sa.Integer(), nullable=False, comment='Target port number'),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'STOPPED', 'ERROR', name='jobstatusenum'), nullable=False, comment='Current job status'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='Scheduled start time for the job'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Scheduled end time for the job'),
    sa.Column('send_count', sa.Integer(), nullable=True, comment='Total number of logs to send (null for unlimited)'),
    sa.Column('send_interval_ms', sa.Integer(), nullable=True, comment='Delay in milliseconds between each log sent'),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['log_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('aaa_role_permission')
    op.drop_index(op.f('ix_aaa_accounts_username'), table_name='aaa_accounts')
    op.drop_index(op.f('ix_aaa_accounts_email'), table_name='aaa_accounts')
    op.drop_table('aaa_accounts')
    op.drop_index(op.f('ix_log_templates_name'), table_name='log_templates')
    op.drop_index(op.f('ix_log_templates_device_type'), table_name='log_templates')
    op.drop_table('log_templates')
    op.drop_index(op.f('ix_aaa_roles_name'), table_name='aaa_roles')
    op.drop_table('aaa_roles')
    op.drop_index(op.f('ix_aaa_permissions_name'), table_name='aaa_permissions')
    op.drop_table('aaa_permissions')
    # ### end Alembic commands ###
